In [529]:
import pandas as pd
import numpy as np
import torch

In [530]:
seed = 42
torch.manual_seed(seed)
np.random.seed(seed)
#random.seed(seed)

In [531]:
df = pd.read_csv("D:/One Drive/OneDrive - University of Bristol/Bristol Data Science/Project/Data/Weather/cleaned_data_weather.csv")

In [532]:
df.head

<bound method NDFrame.head of            date  cloud_cover  sunshine  global_radiation  max_temp  mean_temp  \
0      19790101          2.0       7.0              52.0       2.3       -4.1
1      19790102          6.0       1.7              27.0       1.6       -2.6
2      19790103          5.0       0.0              13.0       1.3       -2.8
3      19790104          8.0       0.0              13.0      -0.3       -2.6
4      19790105          6.0       2.0              29.0       5.6       -0.8
...         ...          ...       ...               ...       ...        ...
15076  20201224          2.0       1.3              32.0       6.1        6.1
15077  20201225          6.0       3.5              40.0       4.6        2.6
15078  20201226          5.8       2.1              38.0      10.0        4.9
15079  20201230          6.0       0.4              22.0       5.6        2.7
15080  20201231          7.0       1.3              34.0       1.5       -0.8

       min_temp  precipitation  pressure  snow_depth
0          -7.5            0.4  101900.0         9.0
1          -7.5            0.0  102530.0         8.0
2          -7.2            0.0  102050.0         4.0
3          -6.5            0.0  100840.0         2.0
4          -1.4            0.0  102250.0         1.0
...         ...            ...       ...         ...
15076       6.1            0.0  101830.0         0.0
15077       0.7            0.0  103100.0         0.0
15078      -0.1           12.0  101960.0         0.0
15079      -0.1            0.0  100200.0         0.0
15080      -3.1            0.0  100500.0         0.0

[15081 rows x 10 columns]>

In [533]:
df_original_data = df

In [534]:
df['next_1_day_mean_temp'] = df_original_data['mean_temp'].shift(-1)
df['next_2_day_mean_temp'] = df_original_data['mean_temp'].shift(-2)
df['next_3_day_mean_temp'] = df_original_data['mean_temp'].shift(-3)
df['next_4_day_mean_temp'] = df_original_data['mean_temp'].shift(-4)
df['next_5_day_mean_temp'] = df_original_data['mean_temp'].shift(-5)
df['next_6_day_mean_temp'] = df_original_data['mean_temp'].shift(-6)
df['next_7_day_mean_temp'] = df_original_data['mean_temp'].shift(-7)

In [535]:
df.dropna(inplace=True)

In [536]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,next_4_day_mean_temp,next_5_day_mean_temp,next_6_day_mean_temp,next_7_day_mean_temp
0,19790101,2.0,7.0,52.0,2.3,-4.1,-7.5,0.4,101900.0,9.0,-2.6,-2.8,-2.6,-0.8,-0.5,1.5,6.9
1,19790102,6.0,1.7,27.0,1.6,-2.6,-7.5,0.0,102530.0,8.0,-2.8,-2.6,-0.8,-0.5,1.5,6.9,3.7
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0.0,102050.0,4.0,-2.6,-0.8,-0.5,1.5,6.9,3.7,2.6
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0.0,100840.0,2.0,-0.8,-0.5,1.5,6.9,3.7,2.6,0.4
4,19790105,6.0,2.0,29.0,5.6,-0.8,-1.4,0.0,102250.0,1.0,-0.5,1.5,6.9,3.7,2.6,0.4,-2.6

#### cloud_cover processing

In [537]:
df['cloud_cover'].value_counts()

7.0    3115
6.0    2951
5.0    2292
8.0    1902
4.0    1815
3.0    1148
2.0     859
1.0     603
0.0     375
5.8       2
6.8       2
5.4       2
7.4       2
9.0       2
5.6       1
6.2       1
6.6       1
7.2       1
Name: cloud_cover, dtype: int64

In [538]:
condition = (df['cloud_cover'] % 1 != 0) | (df['cloud_cover'] > 8.0)

# 从DataFrame中去除满足条件的行
df = df[~condition]

In [539]:
df['cloud_cover'].value_counts()

7.0    3115
6.0    2951
5.0    2292
8.0    1902
4.0    1815
3.0    1148
2.0     859
1.0     603
0.0     375
Name: cloud_cover, dtype: int64

#### change the sunshine into hours

In [540]:
df['sunshine'] = df['sunshine'] * 60

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17252\4129770657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sunshine'] = df['sunshine'] * 60

In [541]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,next_4_day_mean_temp,next_5_day_mean_temp,next_6_day_mean_temp,next_7_day_mean_temp
0,19790101,2.0,420.0,52.0,2.3,-4.1,-7.5,0.4,101900.0,9.0,-2.6,-2.8,-2.6,-0.8,-0.5,1.5,6.9
1,19790102,6.0,102.0,27.0,1.6,-2.6,-7.5,0.0,102530.0,8.0,-2.8,-2.6,-0.8,-0.5,1.5,6.9,3.7
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0.0,102050.0,4.0,-2.6,-0.8,-0.5,1.5,6.9,3.7,2.6
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0.0,100840.0,2.0,-0.8,-0.5,1.5,6.9,3.7,2.6,0.4
4,19790105,6.0,120.0,29.0,5.6,-0.8,-1.4,0.0,102250.0,1.0,-0.5,1.5,6.9,3.7,2.6,0.4,-2.6

#### change snow depth into a category value

In [542]:
df['snow_depth'].value_counts()

0.0     14929
1.0        45
2.0        23
4.0        15
3.0        15
5.0         6
6.0         4
7.0         4
8.0         4
10.0        2
0.4         2
12.0        2
11.0        2
9.0         1
18.0        1
13.0        1
15.0        1
16.0        1
22.0        1
0.8         1
Name: snow_depth, dtype: int64

In [543]:
df.loc[df['snow_depth'] > 0, 'snow_depth'] = 1.0

In [544]:
df['snow_depth'].value_counts()

0.0    14929
1.0      131
Name: snow_depth, dtype: int64

#### change the precipitation into category value

In [545]:
df['precipitation'].value_counts()

0.00     7905
0.20     1005
0.40      452
0.10      313
0.60      296
         ...
53.10       1
18.70       1
25.40       1
20.00       1
0.46        1
Name: precipitation, Length: 261, dtype: int64

In [546]:
bins = [-float('inf'), 0.1, 2.5, 10, 50, float('inf')]
labels = [0, 1, 2, 3, 4]

df['precipitation'] = pd.cut(df['precipitation'], bins=bins, labels=labels, right=False)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17252\1477534085.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['precipitation'] = pd.cut(df['precipitation'], bins=bins, labels=labels, right=False)

In [547]:
df['precipitation'].value_counts()

0    7905
1    4249
2    2335
3     567
4       4
Name: precipitation, dtype: int64

#### everything is ready

In [548]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,next_4_day_mean_temp,next_5_day_mean_temp,next_6_day_mean_temp,next_7_day_mean_temp
0,19790101,2.0,420.0,52.0,2.3,-4.1,-7.5,1,101900.0,1.0,-2.6,-2.8,-2.6,-0.8,-0.5,1.5,6.9
1,19790102,6.0,102.0,27.0,1.6,-2.6,-7.5,0,102530.0,1.0,-2.8,-2.6,-0.8,-0.5,1.5,6.9,3.7
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0,102050.0,1.0,-2.6,-0.8,-0.5,1.5,6.9,3.7,2.6
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0,100840.0,1.0,-0.8,-0.5,1.5,6.9,3.7,2.6,0.4
4,19790105,6.0,120.0,29.0,5.6,-0.8,-1.4,0,102250.0,1.0,-0.5,1.5,6.9,3.7,2.6,0.4,-2.6

#### one-hot encoding

In [549]:
df_encoded = pd.get_dummies(df['cloud_cover'], prefix='cloud_cover')

df = pd.concat([df, df_encoded], axis=1)

df.drop('cloud_cover', axis=1, inplace=True)

In [550]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,...,next_7_day_mean_temp,cloud_cover_0.0,cloud_cover_1.0,cloud_cover_2.0,cloud_cover_3.0,cloud_cover_4.0,cloud_cover_5.0,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0
0,19790101,420.0,52.0,2.3,-4.1,-7.5,1,101900.0,1.0,-2.6,...,6.9,0,0,1,0,0,0,0,0,0
1,19790102,102.0,27.0,1.6,-2.6,-7.5,0,102530.0,1.0,-2.8,...,3.7,0,0,0,0,0,0,1,0,0
2,19790103,0.0,13.0,1.3,-2.8,-7.2,0,102050.0,1.0,-2.6,...,2.6,0,0,0,0,0,1,0,0,0
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,0,100840.0,1.0,-0.8,...,0.4,0,0,0,0,0,0,0,0,1
4,19790105,120.0,29.0,5.6,-0.8,-1.4,0,102250.0,1.0,-0.5,...,-2.6,0,0,0,0,0,0,1,0,0

In [551]:
df_encoded = pd.get_dummies(df['precipitation'], prefix='precipitation')

df = pd.concat([df, df_encoded], axis=1)

df.drop('precipitation', axis=1, inplace=True)

In [552]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,...,cloud_cover_4.0,cloud_cover_5.0,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4
0,19790101,420.0,52.0,2.3,-4.1,-7.5,101900.0,1.0,-2.6,-2.8,...,0,0,0,0,0,0,1,0,0,0
1,19790102,102.0,27.0,1.6,-2.6,-7.5,102530.0,1.0,-2.8,-2.6,...,0,0,1,0,0,1,0,0,0,0
2,19790103,0.0,13.0,1.3,-2.8,-7.2,102050.0,1.0,-2.6,-0.8,...,0,1,0,0,0,1,0,0,0,0
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,100840.0,1.0,-0.8,-0.5,...,0,0,0,0,1,1,0,0,0,0
4,19790105,120.0,29.0,5.6,-0.8,-1.4,102250.0,1.0,-0.5,1.5,...,0,0,1,0,0,1,0,0,0,0

In [553]:
df_encoded = pd.get_dummies(df['snow_depth'], prefix='snow_depth')

df = pd.concat([df, df_encoded], axis=1)

df.drop('snow_depth', axis=1, inplace=True)

In [554]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,19790101,420.0,52.0,2.3,-4.1,-7.5,101900.0,-2.6,-2.8,-2.6,...,0,0,0,0,1,0,0,0,0,1
1,19790102,102.0,27.0,1.6,-2.6,-7.5,102530.0,-2.8,-2.6,-0.8,...,1,0,0,1,0,0,0,0,0,1
2,19790103,0.0,13.0,1.3,-2.8,-7.2,102050.0,-2.6,-0.8,-0.5,...,0,0,0,1,0,0,0,0,0,1
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,100840.0,-0.8,-0.5,1.5,...,0,0,1,1,0,0,0,0,0,1
4,19790105,120.0,29.0,5.6,-0.8,-1.4,102250.0,-0.5,1.5,6.9,...,1,0,0,1,0,0,0,0,0,1

#### delete the date

In [555]:
del df['date']

In [556]:
df.head()

,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,next_4_day_mean_temp,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,420.0,52.0,2.3,-4.1,-7.5,101900.0,-2.6,-2.8,-2.6,-0.8,...,0,0,0,0,1,0,0,0,0,1
1,102.0,27.0,1.6,-2.6,-7.5,102530.0,-2.8,-2.6,-0.8,-0.5,...,1,0,0,1,0,0,0,0,0,1
2,0.0,13.0,1.3,-2.8,-7.2,102050.0,-2.6,-0.8,-0.5,1.5,...,0,0,0,1,0,0,0,0,0,1
3,0.0,13.0,-0.3,-2.6,-6.5,100840.0,-0.8,-0.5,1.5,6.9,...,0,0,1,1,0,0,0,0,0,1
4,120.0,29.0,5.6,-0.8,-1.4,102250.0,-0.5,1.5,6.9,3.7,...,1,0,0,1,0,0,0,0,0,1

In [557]:
from sklearn.preprocessing import MinMaxScaler

features_to_normalize = ['sunshine', 'global_radiation', 'max_temp', 'mean_temp', 'min_temp', 'pressure']

scaler = MinMaxScaler()


df[features_to_normalize] = scaler.fit_transform(df[features_to_normalize])

In [558]:
df.head()

,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,next_4_day_mean_temp,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,0.43750,0.107143,0.161538,0.037791,0.044872,0.562738,-2.6,-2.8,-2.6,-0.8,...,0,0,0,0,1,0,0,0,0,1
1,0.10625,0.043367,0.143590,0.081395,0.044872,0.682510,-2.8,-2.6,-0.8,-0.5,...,1,0,0,1,0,0,0,0,0,1
2,0.00000,0.007653,0.135897,0.075581,0.054487,0.591255,-2.6,-0.8,-0.5,1.5,...,0,0,0,1,0,0,0,0,0,1
3,0.00000,0.007653,0.094872,0.081395,0.076923,0.361217,-0.8,-0.5,1.5,6.9,...,0,0,1,1,0,0,0,0,0,1
4,0.12500,0.048469,0.246154,0.133721,0.240385,0.629278,-0.5,1.5,6.9,3.7,...,1,0,0,1,0,0,0,0,0,1

#### check if any INF or NAN

In [559]:
inf_check = np.isinf(df)
print(inf_check.any())

sunshine                False
global_radiation        False
max_temp                False
mean_temp               False
min_temp                False
pressure                False
next_1_day_mean_temp    False
next_2_day_mean_temp    False
next_3_day_mean_temp    False
next_4_day_mean_temp    False
next_5_day_mean_temp    False
next_6_day_mean_temp    False
next_7_day_mean_temp    False
cloud_cover_0.0         False
cloud_cover_1.0         False
cloud_cover_2.0         False
cloud_cover_3.0         False
cloud_cover_4.0         False
cloud_cover_5.0         False
cloud_cover_6.0         False
cloud_cover_7.0         False
cloud_cover_8.0         False
precipitation_0         False
precipitation_1         False
precipitation_2         False
precipitation_3         False
precipitation_4         False
snow_depth_0.0          False
snow_depth_1.0          False
dtype: bool

In [560]:
inf_check = np.isnan(df)
print(inf_check.any())

sunshine                False
global_radiation        False
max_temp                False
mean_temp               False
min_temp                False
pressure                False
next_1_day_mean_temp    False
next_2_day_mean_temp    False
next_3_day_mean_temp    False
next_4_day_mean_temp    False
next_5_day_mean_temp    False
next_6_day_mean_temp    False
next_7_day_mean_temp    False
cloud_cover_0.0         False
cloud_cover_1.0         False
cloud_cover_2.0         False
cloud_cover_3.0         False
cloud_cover_4.0         False
cloud_cover_5.0         False
cloud_cover_6.0         False
cloud_cover_7.0         False
cloud_cover_8.0         False
precipitation_0         False
precipitation_1         False
precipitation_2         False
precipitation_3         False
precipitation_4         False
snow_depth_0.0          False
snow_depth_1.0          False
dtype: bool

In [561]:
from sklearn.model_selection import train_test_split


X = df.drop(['next_1_day_mean_temp','next_2_day_mean_temp','next_3_day_mean_temp','next_4_day_mean_temp','next_5_day_mean_temp','next_6_day_mean_temp','next_7_day_mean_temp'], axis=1)
y = df[['next_1_day_mean_temp', 'next_2_day_mean_temp', 'next_3_day_mean_temp','next_4_day_mean_temp','next_5_day_mean_temp','next_6_day_mean_temp','next_7_day_mean_temp']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [562]:


# 划分训练集为新的训练集和验证集
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# 打印划分后的数据集大小
print("train dataset:", X_train.shape)
print("validation dataset:", X_val.shape)
print("test dataset:", X_test.shape)

train dataset: (9638, 22)
validation dataset: (2410, 22)
test dataset: (3012, 22)

In [563]:
import torch
import torch.nn as nn
import torch.optim as optim

X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val.values, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

In [564]:
from torch.utils.data import DataLoader, TensorDataset

# Create a TensorDataset from the tensors
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

# Specify the batch size
batch_size = 128

# Create DataLoaders for training, validation, and testing
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

In [565]:
from scipy.stats import pearsonr

class MLP(nn.Module):
        def __init__(self, input_size, hidden_sizes, output_size, activation=nn.Tanh()):
            super(MLP, self).__init__()

            # Create a list to store the layers
            layers = []

            # Add the input layer
            layers.append(nn.Linear(input_size, hidden_sizes[0]))
            layers.append(activation)

            # Add the hidden layers
            for i in range(1, len(hidden_sizes)):
                layers.append(nn.Linear(hidden_sizes[i-1], hidden_sizes[i]))
                layers.append(activation)

            # Add the output layer
            layers.append(nn.Linear(hidden_sizes[-1], output_size))

            # Create a sequential model using the layers list
            self.model = nn.Sequential(*layers)

        def forward(self, x):
            out = self.model(x)
            return out

In [566]:

# 设置超参数
input_size = X_train.shape[1]
hidden_sizes = [500,200,20]
output_size = y_train.shape[1]
learning_rate = 0.0007
num_epochs = 1000

In [567]:
# 定义早停函数
def early_stopping(val_loss, patience=10, delta=0):
    if len(val_loss) < patience + 1:
        return False
    
    best_loss = min(val_loss[:-patience])
    last_loss = val_loss[-1]

    if last_loss > best_loss - delta:
        return True

    return False

In [568]:
def train_and_validate_model(model, train_loader, val_loader, optimizer, criterion, num_epochs, patience=5, delta=0):    
    
    train_loss_history = []
    val_loss_history = []
    best_model_state = None


    # 训练模型
    for epoch in range(num_epochs):
        model.train()
        train_total_loss = 0.0
        for i, (X_batch, y_batch) in enumerate(train_loader):
            # Clear gradients from the previous iteration
            optimizer.zero_grad()

            # Forward pass: compute model predictions
            predictions = model(X_batch)
            #print('here is prediction：', predictions.shape)

            # Compute the loss
            loss = criterion(predictions, y_batch)
            #print('here is loss：', loss.shape)

            # Backpropagation: compute gradients of the loss with respect to model parameters
            loss.backward()

            # Optimization: update model parameters using the gradients
            optimizer.step()

            # Accumulate the total loss for this epoch
            train_total_loss += loss.item()

            #print(total_loss)
        # Calculate the average loss for this epoch
        train_loss = train_total_loss / len(train_loader)
        train_loss_history.append(train_loss)
        #print(average_loss)

        if (epoch + 1) % 1 == 0:
            print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {train_loss:.4f}')



        model.eval()
        with torch.no_grad():
            val_total_loss = 0.0
            for batch_X, batch_y in val_loader:
                predictions = model(batch_X)
                loss = criterion(predictions, batch_y)
                val_total_loss += loss.item()
            validation_loss = val_total_loss / len(val_loader)
            val_loss_history.append(validation_loss)


        # 检查是否早停
        if early_stopping(val_loss_history, patience, delta):
            print("Early stopping triggered!")
            best_model_state = model.state_dict()
            break
    
    print('final epoch: ', epoch)
    return best_model_state

In [569]:
# 初始化模型和优化器
model = MLP(input_size, hidden_sizes, output_size)
optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=0.000546323217)
#optimizer = optim.Adam(model.parameters())
criterion = nn.MSELoss()

best_model_state = train_and_validate_model(model, train_loader, val_loader, optimizer, criterion, num_epochs=num_epochs, patience=30, delta=0.005)

Epoch [1/1000], Loss: 135.4213
Epoch [2/1000], Loss: 111.9277
Epoch [3/1000], Loss: 94.5042
Epoch [4/1000], Loss: 80.9017
Epoch [5/1000], Loss: 69.1205
Epoch [6/1000], Loss: 59.8126
Epoch [7/1000], Loss: 52.5224
Epoch [8/1000], Loss: 46.9454
Epoch [9/1000], Loss: 41.2276
Epoch [10/1000], Loss: 34.7437
Epoch [11/1000], Loss: 30.2144
Epoch [12/1000], Loss: 26.4485
Epoch [13/1000], Loss: 23.3589
Epoch [14/1000], Loss: 20.6984
Epoch [15/1000], Loss: 18.5260
Epoch [16/1000], Loss: 16.7611
Epoch [17/1000], Loss: 15.2265
Epoch [18/1000], Loss: 13.9361
Epoch [19/1000], Loss: 12.9043
Epoch [20/1000], Loss: 11.9712
Epoch [21/1000], Loss: 11.2310
Epoch [22/1000], Loss: 10.6151
Epoch [23/1000], Loss: 10.0251
Epoch [24/1000], Loss: 9.6042
Epoch [25/1000], Loss: 9.2418
Epoch [26/1000], Loss: 8.9356
Epoch [27/1000], Loss: 8.6307
Epoch [28/1000], Loss: 8.4454
Epoch [29/1000], Loss: 8.2592
Epoch [30/1000], Loss: 8.0661
Epoch [31/1000], Loss: 7.9503
Epoch [32/1000], Loss: 7.8076
Epoch [33/1000], Loss: 7.6759
Epoch [34/1000], Loss: 7.6062
Epoch [35/1000], Loss: 7.5910
Epoch [36/1000], Loss: 7.4769
Epoch [37/1000], Loss: 7.4286
Epoch [38/1000], Loss: 7.3382
Epoch [39/1000], Loss: 7.3370
Epoch [40/1000], Loss: 7.3052
Epoch [41/1000], Loss: 7.2769
Epoch [42/1000], Loss: 7.2499
Epoch [43/1000], Loss: 7.1961
Epoch [44/1000], Loss: 7.1781
Epoch [45/1000], Loss: 7.1611
Epoch [46/1000], Loss: 7.1082
Epoch [47/1000], Loss: 7.0740
Epoch [48/1000], Loss: 7.1101
Epoch [49/1000], Loss: 7.0586
Epoch [50/1000], Loss: 7.0773
Epoch [51/1000], Loss: 7.0348
Epoch [52/1000], Loss: 7.0045
Epoch [53/1000], Loss: 7.0896
Epoch [54/1000], Loss: 6.9969
Epoch [55/1000], Loss: 7.0070
Epoch [56/1000], Loss: 6.9815
Epoch [57/1000], Loss: 6.9733
Epoch [58/1000], Loss: 6.9685
Epoch [59/1000], Loss: 6.9768
Epoch [60/1000], Loss: 6.9535
Epoch [61/1000], Loss: 6.9263
Epoch [62/1000], Loss: 6.9126
Epoch [63/1000], Loss: 6.9423
Epoch [64/1000], Loss: 6.9159
Epoch [65/1000], Loss: 6.9161
Epoch [66/1000], Loss: 6.9054
Epoch [67/1000], Loss: 6.8766
Epoch [68/1000], Loss: 6.8586
Epoch [69/1000], Loss: 6.8802
Epoch [70/1000], Loss: 6.8865
Epoch [71/1000], Loss: 6.8429
Epoch [72/1000], Loss: 6.8569
Epoch [73/1000], Loss: 6.8423
Epoch [74/1000], Loss: 6.8575
Epoch [75/1000], Loss: 6.8509
Epoch [76/1000], Loss: 6.8433
Epoch [77/1000], Loss: 6.8082
Epoch [78/1000], Loss: 6.7861
Epoch [79/1000], Loss: 6.8140
Epoch [80/1000], Loss: 6.7548
Epoch [81/1000], Loss: 6.7997
Epoch [82/1000], Loss: 6.7754
Epoch [83/1000], Loss: 6.7763
Epoch [84/1000], Loss: 6.7528
Epoch [85/1000], Loss: 6.7720
Epoch [86/1000], Loss: 6.7272
Epoch [87/1000], Loss: 6.7061
Epoch [88/1000], Loss: 6.7398
Epoch [89/1000], Loss: 6.7005
Epoch [90/1000], Loss: 6.6951
Epoch [91/1000], Loss: 6.6669
Epoch [92/1000], Loss: 6.6573
Epoch [93/1000], Loss: 6.6411
Epoch [94/1000], Loss: 6.6272
Epoch [95/1000], Loss: 6.6226
Epoch [96/1000], Loss: 6.6491
Epoch [97/1000], Loss: 6.6091
Epoch [98/1000], Loss: 6.5421
Epoch [99/1000], Loss: 6.5522
Epoch [100/1000], Loss: 6.5323
Epoch [101/1000], Loss: 6.5205
Epoch [102/1000], Loss: 6.4841
Epoch [103/1000], Loss: 6.5080
Epoch [104/1000], Loss: 6.4755
Epoch [105/1000], Loss: 6.4462
Epoch [106/1000], Loss: 6.4522
Epoch [107/1000], Loss: 6.4260
Epoch [108/1000], Loss: 6.4030
Epoch [109/1000], Loss: 6.4525
Epoch [110/1000], Loss: 6.3791
Epoch [111/1000], Loss: 6.3750
Epoch [112/1000], Loss: 6.4074
Epoch [113/1000], Loss: 6.3888
Epoch [114/1000], Loss: 6.3544
Epoch [115/1000], Loss: 6.3749
Epoch [116/1000], Loss: 6.3599
Epoch [117/1000], Loss: 6.3713
Epoch [118/1000], Loss: 6.3613
Epoch [119/1000], Loss: 6.3472
Epoch [120/1000], Loss: 6.3228
Epoch [121/1000], Loss: 6.3422
Epoch [122/1000], Loss: 6.3509
Epoch [123/1000], Loss: 6.3588
Epoch [124/1000], Loss: 6.3273
Epoch [125/1000], Loss: 6.3277
Epoch [126/1000], Loss: 6.3333
Epoch [127/1000], Loss: 6.3291
Epoch [128/1000], Loss: 6.3065
Epoch [129/1000], Loss: 6.3130
Epoch [130/1000], Loss: 6.2991
Epoch [131/1000], Loss: 6.2923
Epoch [132/1000], Loss: 6.2825
Epoch [133/1000], Loss: 6.2690
Epoch [134/1000], Loss: 6.2837
Epoch [135/1000], Loss: 6.2845
Epoch [136/1000], Loss: 6.2787
Epoch [137/1000], Loss: 6.2936
Epoch [138/1000], Loss: 6.2775
Epoch [139/1000], Loss: 6.2252
Epoch [140/1000], Loss: 6.2712
Epoch [141/1000], Loss: 6.2458
Epoch [142/1000], Loss: 6.2525
Epoch [143/1000], Loss: 6.2378
Epoch [144/1000], Loss: 6.2525
Epoch [145/1000], Loss: 6.2464
Epoch [146/1000], Loss: 6.2535
Epoch [147/1000], Loss: 6.2134
Epoch [148/1000], Loss: 6.2015
Epoch [149/1000], Loss: 6.2050
Epoch [150/1000], Loss: 6.2044
Early stopping triggered!
final epoch:  149

In [570]:
#model.load_state_dict(best_model_state)

In [571]:
with torch.no_grad():
    total_mse = 0.0
    for batch_X, batch_y in val_loader:
        # Forward pass: compute model predictions
        predictions = model(batch_X)

        # Compute the loss (assuming you have defined the loss function as 'criterion')
        mse = criterion(predictions, batch_y)

        # Accumulate the total loss for this validation set
        total_mse += mse.item()

    # Calculate the average loss for the entire validation set
    #print(total_mse)
    mse_loss = total_mse / len(val_loader)

In [572]:
mse_loss

6.541353100224545

In [ ]:
3.855835475419697  / 62

In [ ]:
with torch.no_grad():
    predictions = model(X_test_tensor)
    
    test_mse = criterion(predictions, y_test_tensor)
    
    '''
    test_mae = nn.L1Loss()(predictions, y_test_tensor)
    
    test_rmse = torch.sqrt(test_mse)
    
    absolute_errors = torch.abs(predictions - y_test_tensor)
    test_mdae = torch.median(absolute_errors)
    
    percentage_errors = absolute_errors / y_test_tensor
    percentage_errors = percentage_errors[~torch.isinf(percentage_errors)]
    test_mape = torch.mean(percentage_errors) * 100
    
    squared_percentage_errors = torch.pow(percentage_errors * 100, 2)
    squared_percentage_errors = squared_percentage_errors[~torch.isinf(squared_percentage_errors)]
    mean_squared_percentage_error = torch.mean(squared_percentage_errors)
    test_rmspe = torch.sqrt(mean_squared_percentage_error)
    
    pearson_coefficient, _ = pearsonr(predictions.numpy().flatten(), y_test_tensor.numpy().flatten())
    
    
    def index_of_agreement(predictions, observations):
        numerator = torch.sum(torch.square(observations - predictions))
        denominator = torch.sum(torch.square(torch.abs(predictions - torch.mean(observations)) + torch.abs(observations - torch.mean(observations))))
        ioa = 1 - (numerator / denominator)
        return ioa
    
    ioa = index_of_agreement(predictions, y_test_tensor)
'''

    

    

print(f'MSE: {test_mse.item():.4f}')
#print(f'RMSE: {test_rmse.item():.4f}')
#print(f'MAE: {test_mae.item():.4f}')
#print(f'MdAE: {test_mdae.item():.4f}')
#print(f'MAPE: {test_mape.item():.4f}')
#print(f'RMSPE: {test_rmspe.item():.4f}')
#print(f'Pearson Correlation Coefficient: {pearson_coefficient:.4f}')
#print(f'Index of Agreement (IoA): {ioa:.4f}')

##### search space

In [ ]:
varbound = np.array([[0.001, 0.1],        # 学习率范围
                     [1, 5],             # 隐藏层的层数范围
                     [10, 100],          # 每一层的节点数范围
                     [16, 128],          # batch size范围
                     [0, 2]])            # 激活函数选择，例如0表示Sigmoid，1表示ReLU，2表示Tanh

##### fitness function

In [ ]:
def MLP_fitness_function(params):
    # 解码参数
    learning_rate = params[0]
    hidden_layers = int(params[1])
    nodes_per_layer = int(params[2])
    batch_size = int(params[3])
    activation_function = ['logistic', 'relu', 'tanh'][int(params[4])]
    
    mlp = MLPRegressor(hidden_layer_sizes=(nodes_per_layer,) * hidden_layers,
                       activation=activation_function,
                       learning_rate_init=learning_rate,
                       batch_size=batch_size,
                       random_state=42)
    # 使用训练数据训练MLP
    mlp.fit(X_train, y_train)

    # 使用验证数据评估MLP性能（均方误差）
    y_pred = mlp.predict(X_val)
    mse = mean_squared_error(y_val, y_pred)

    # 因为遗传算法是最小化问题，我们将均方误差转换为负值
    return -mse

In [ ]:
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from geneticalgorithm import geneticalgorithm as ga


# 创建遗传算法对象
algorithm_param = {'max_num_iteration': 100, 'population_size': 10, 'elit_ratio': 0.01,
                   'parents_portion': 0.3, 'crossover_probability': 0.5, 'mutation_probability': 0.2, 
                   'crossover_type':'uniform', 'max_iteration_without_improv': None}
model = ga(function=MLP_fitness_function, dimension=5, variable_type='real', variable_boundaries=varbound,
           algorithm_parameters=algorithm_param, function_timeout = 100)

# 运行遗传算法进行优化
model.run()

# 获得优化的超参数组合
best_params = model.output_dict['variable']

# 使用优化的超参数训练最终的MLP回归模型
learning_rate = best_params[0]
hidden_layers = int(best_params[1])
nodes_per_layer = int(best_params[2])
batch_size = int(best_params[3])
activation_function = ['logistic', 'relu', 'tanh'][int(best_params[4])]

final_mlp = MLPRegressor(hidden_layer_sizes=(nodes_per_layer,) * hidden_layers,
                         activation=activation_function,
                         learning_rate_init=learning_rate,
                         batch_size=batch_size,
                         random_state=42)

final_mlp.fit(X_train, y_train)

# 使用测试数据评估最终的MLP回归模型性能（均方误差）
y_pred_test = final_mlp.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)

print("最优超参数组合：", best_params)
print("最终测试均方误差：", test_mse)