In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:/One Drive/OneDrive - University of Bristol/Bristol Data Science/Project/Data/Weather/cleaned_data_weather.csv")

In [3]:
df.head

<bound method NDFrame.head of            date  cloud_cover  sunshine  global_radiation  max_temp  mean_temp  \
0      19790101          2.0       7.0              52.0       2.3       -4.1
1      19790102          6.0       1.7              27.0       1.6       -2.6
2      19790103          5.0       0.0              13.0       1.3       -2.8
3      19790104          8.0       0.0              13.0      -0.3       -2.6
4      19790105          6.0       2.0              29.0       5.6       -0.8
...         ...          ...       ...               ...       ...        ...
15076  20201224          2.0       1.3              32.0       6.1        6.1
15077  20201225          6.0       3.5              40.0       4.6        2.6
15078  20201226          5.8       2.1              38.0      10.0        4.9
15079  20201230          6.0       0.4              22.0       5.6        2.7
15080  20201231          7.0       1.3              34.0       1.5       -0.8

       min_temp  precipitation  pressure  snow_depth
0          -7.5            0.4  101900.0         9.0
1          -7.5            0.0  102530.0         8.0
2          -7.2            0.0  102050.0         4.0
3          -6.5            0.0  100840.0         2.0
4          -1.4            0.0  102250.0         1.0
...         ...            ...       ...         ...
15076       6.1            0.0  101830.0         0.0
15077       0.7            0.0  103100.0         0.0
15078      -0.1           12.0  101960.0         0.0
15079      -0.1            0.0  100200.0         0.0
15080      -3.1            0.0  100500.0         0.0

[15081 rows x 10 columns]>

In [4]:
df_original_data = df

In [5]:
df['next_1_day_mean_temp'] = df_original_data['mean_temp'].shift(-1)
df['next_2_day_mean_temp'] = df_original_data['mean_temp'].shift(-2)
df['next_3_day_mean_temp'] = df_original_data['mean_temp'].shift(-3)

In [6]:
df.dropna(inplace=True)

In [7]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp
0,19790101,2.0,7.0,52.0,2.3,-4.1,-7.5,0.4,101900.0,9.0,-2.6,-2.8,-2.6
1,19790102,6.0,1.7,27.0,1.6,-2.6,-7.5,0.0,102530.0,8.0,-2.8,-2.6,-0.8
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0.0,102050.0,4.0,-2.6,-0.8,-0.5
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0.0,100840.0,2.0,-0.8,-0.5,1.5
4,19790105,6.0,2.0,29.0,5.6,-0.8,-1.4,0.0,102250.0,1.0,-0.5,1.5,6.9

#### cloud_cover processing

In [8]:
df['cloud_cover'].value_counts()

7.0    3116
6.0    2952
5.0    2292
8.0    1903
4.0    1815
3.0    1148
2.0     860
1.0     603
0.0     375
5.8       2
6.8       2
5.4       2
7.4       2
9.0       2
5.6       1
6.2       1
6.6       1
7.2       1
Name: cloud_cover, dtype: int64

In [9]:
condition = (df['cloud_cover'] % 1 != 0) | (df['cloud_cover'] > 8.0)

# 从DataFrame中去除满足条件的行
df = df[~condition]

In [10]:
df['cloud_cover'].value_counts()

7.0    3116
6.0    2952
5.0    2292
8.0    1903
4.0    1815
3.0    1148
2.0     860
1.0     603
0.0     375
Name: cloud_cover, dtype: int64

#### change the sunshine into hours

In [11]:
df['sunshine'] = df['sunshine'] * 60

C:\Users\Administrator\AppData\Local\Temp\ipykernel_28300\4129770657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sunshine'] = df['sunshine'] * 60

In [12]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp
0,19790101,2.0,420.0,52.0,2.3,-4.1,-7.5,0.4,101900.0,9.0,-2.6,-2.8,-2.6
1,19790102,6.0,102.0,27.0,1.6,-2.6,-7.5,0.0,102530.0,8.0,-2.8,-2.6,-0.8
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0.0,102050.0,4.0,-2.6,-0.8,-0.5
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0.0,100840.0,2.0,-0.8,-0.5,1.5
4,19790105,6.0,120.0,29.0,5.6,-0.8,-1.4,0.0,102250.0,1.0,-0.5,1.5,6.9

#### change snow depth into a category value

In [13]:
df['snow_depth'].value_counts()

0.0     14933
1.0        45
2.0        23
4.0        15
3.0        15
5.0         6
6.0         4
7.0         4
8.0         4
10.0        2
0.4         2
12.0        2
11.0        2
9.0         1
18.0        1
13.0        1
15.0        1
16.0        1
22.0        1
0.8         1
Name: snow_depth, dtype: int64

In [14]:
df.loc[df['snow_depth'] > 0, 'snow_depth'] = 1.0

In [15]:
df['snow_depth'].value_counts()

0.0    14933
1.0      131
Name: snow_depth, dtype: int64

#### change the precipitation into category value

In [16]:
df['precipitation'].value_counts()

0.00     7907
0.20     1005
0.40      452
0.10      313
0.60      297
         ...
53.10       1
18.70       1
25.40       1
20.00       1
0.46        1
Name: precipitation, Length: 261, dtype: int64

In [17]:
bins = [-float('inf'), 0.1, 2.5, 10, 50, float('inf')]
labels = [0, 1, 2, 3, 4]

df['precipitation'] = pd.cut(df['precipitation'], bins=bins, labels=labels, right=False)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_28300\1477534085.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['precipitation'] = pd.cut(df['precipitation'], bins=bins, labels=labels, right=False)

In [18]:
df['precipitation'].value_counts()

0    7907
1    4251
2    2335
3     567
4       4
Name: precipitation, dtype: int64

#### everything is ready

In [19]:
df.head()

,date,cloud_cover,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp
0,19790101,2.0,420.0,52.0,2.3,-4.1,-7.5,1,101900.0,1.0,-2.6,-2.8,-2.6
1,19790102,6.0,102.0,27.0,1.6,-2.6,-7.5,0,102530.0,1.0,-2.8,-2.6,-0.8
2,19790103,5.0,0.0,13.0,1.3,-2.8,-7.2,0,102050.0,1.0,-2.6,-0.8,-0.5
3,19790104,8.0,0.0,13.0,-0.3,-2.6,-6.5,0,100840.0,1.0,-0.8,-0.5,1.5
4,19790105,6.0,120.0,29.0,5.6,-0.8,-1.4,0,102250.0,1.0,-0.5,1.5,6.9

#### one-hot encoding

In [20]:
df_encoded = pd.get_dummies(df['cloud_cover'], prefix='cloud_cover')

df = pd.concat([df, df_encoded], axis=1)

df.drop('cloud_cover', axis=1, inplace=True)

In [21]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,precipitation,pressure,snow_depth,next_1_day_mean_temp,...,next_3_day_mean_temp,cloud_cover_0.0,cloud_cover_1.0,cloud_cover_2.0,cloud_cover_3.0,cloud_cover_4.0,cloud_cover_5.0,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0
0,19790101,420.0,52.0,2.3,-4.1,-7.5,1,101900.0,1.0,-2.6,...,-2.6,0,0,1,0,0,0,0,0,0
1,19790102,102.0,27.0,1.6,-2.6,-7.5,0,102530.0,1.0,-2.8,...,-0.8,0,0,0,0,0,0,1,0,0
2,19790103,0.0,13.0,1.3,-2.8,-7.2,0,102050.0,1.0,-2.6,...,-0.5,0,0,0,0,0,1,0,0,0
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,0,100840.0,1.0,-0.8,...,1.5,0,0,0,0,0,0,0,0,1
4,19790105,120.0,29.0,5.6,-0.8,-1.4,0,102250.0,1.0,-0.5,...,6.9,0,0,0,0,0,0,1,0,0

In [22]:
df_encoded = pd.get_dummies(df['precipitation'], prefix='precipitation')

df = pd.concat([df, df_encoded], axis=1)

df.drop('precipitation', axis=1, inplace=True)

In [23]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,snow_depth,next_1_day_mean_temp,next_2_day_mean_temp,...,cloud_cover_4.0,cloud_cover_5.0,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4
0,19790101,420.0,52.0,2.3,-4.1,-7.5,101900.0,1.0,-2.6,-2.8,...,0,0,0,0,0,0,1,0,0,0
1,19790102,102.0,27.0,1.6,-2.6,-7.5,102530.0,1.0,-2.8,-2.6,...,0,0,1,0,0,1,0,0,0,0
2,19790103,0.0,13.0,1.3,-2.8,-7.2,102050.0,1.0,-2.6,-0.8,...,0,1,0,0,0,1,0,0,0,0
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,100840.0,1.0,-0.8,-0.5,...,0,0,0,0,1,1,0,0,0,0
4,19790105,120.0,29.0,5.6,-0.8,-1.4,102250.0,1.0,-0.5,1.5,...,0,0,1,0,0,1,0,0,0,0

In [24]:
df_encoded = pd.get_dummies(df['snow_depth'], prefix='snow_depth')

df = pd.concat([df, df_encoded], axis=1)

df.drop('snow_depth', axis=1, inplace=True)

In [25]:
df.head()

,date,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,19790101,420.0,52.0,2.3,-4.1,-7.5,101900.0,-2.6,-2.8,-2.6,...,0,0,0,0,1,0,0,0,0,1
1,19790102,102.0,27.0,1.6,-2.6,-7.5,102530.0,-2.8,-2.6,-0.8,...,1,0,0,1,0,0,0,0,0,1
2,19790103,0.0,13.0,1.3,-2.8,-7.2,102050.0,-2.6,-0.8,-0.5,...,0,0,0,1,0,0,0,0,0,1
3,19790104,0.0,13.0,-0.3,-2.6,-6.5,100840.0,-0.8,-0.5,1.5,...,0,0,1,1,0,0,0,0,0,1
4,19790105,120.0,29.0,5.6,-0.8,-1.4,102250.0,-0.5,1.5,6.9,...,1,0,0,1,0,0,0,0,0,1

#### delete the date

In [26]:
del df['date']

In [27]:
df.head()

,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,cloud_cover_0.0,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,420.0,52.0,2.3,-4.1,-7.5,101900.0,-2.6,-2.8,-2.6,0,...,0,0,0,0,1,0,0,0,0,1
1,102.0,27.0,1.6,-2.6,-7.5,102530.0,-2.8,-2.6,-0.8,0,...,1,0,0,1,0,0,0,0,0,1
2,0.0,13.0,1.3,-2.8,-7.2,102050.0,-2.6,-0.8,-0.5,0,...,0,0,0,1,0,0,0,0,0,1
3,0.0,13.0,-0.3,-2.6,-6.5,100840.0,-0.8,-0.5,1.5,0,...,0,0,1,1,0,0,0,0,0,1
4,120.0,29.0,5.6,-0.8,-1.4,102250.0,-0.5,1.5,6.9,0,...,1,0,0,1,0,0,0,0,0,1

In [28]:
from sklearn.preprocessing import MinMaxScaler

features_to_normalize = ['sunshine', 'global_radiation', 'max_temp', 'mean_temp', 'min_temp', 'pressure']

scaler = MinMaxScaler()


df[features_to_normalize] = scaler.fit_transform(df[features_to_normalize])

In [29]:
df.head()

,sunshine,global_radiation,max_temp,mean_temp,min_temp,pressure,next_1_day_mean_temp,next_2_day_mean_temp,next_3_day_mean_temp,cloud_cover_0.0,...,cloud_cover_6.0,cloud_cover_7.0,cloud_cover_8.0,precipitation_0,precipitation_1,precipitation_2,precipitation_3,precipitation_4,snow_depth_0.0,snow_depth_1.0
0,0.43750,0.107143,0.161538,0.037791,0.044872,0.562738,-2.6,-2.8,-2.6,0,...,0,0,0,0,1,0,0,0,0,1
1,0.10625,0.043367,0.143590,0.081395,0.044872,0.682510,-2.8,-2.6,-0.8,0,...,1,0,0,1,0,0,0,0,0,1
2,0.00000,0.007653,0.135897,0.075581,0.054487,0.591255,-2.6,-0.8,-0.5,0,...,0,0,0,1,0,0,0,0,0,1
3,0.00000,0.007653,0.094872,0.081395,0.076923,0.361217,-0.8,-0.5,1.5,0,...,0,0,1,1,0,0,0,0,0,1
4,0.12500,0.048469,0.246154,0.133721,0.240385,0.629278,-0.5,1.5,6.9,0,...,1,0,0,1,0,0,0,0,0,1

#### check if any INF or NAN

In [30]:
inf_check = np.isinf(df)
print(inf_check.any())

sunshine                False
global_radiation        False
max_temp                False
mean_temp               False
min_temp                False
pressure                False
next_1_day_mean_temp    False
next_2_day_mean_temp    False
next_3_day_mean_temp    False
cloud_cover_0.0         False
cloud_cover_1.0         False
cloud_cover_2.0         False
cloud_cover_3.0         False
cloud_cover_4.0         False
cloud_cover_5.0         False
cloud_cover_6.0         False
cloud_cover_7.0         False
cloud_cover_8.0         False
precipitation_0         False
precipitation_1         False
precipitation_2         False
precipitation_3         False
precipitation_4         False
snow_depth_0.0          False
snow_depth_1.0          False
dtype: bool

In [31]:
inf_check = np.isnan(df)
print(inf_check.any())

sunshine                False
global_radiation        False
max_temp                False
mean_temp               False
min_temp                False
pressure                False
next_1_day_mean_temp    False
next_2_day_mean_temp    False
next_3_day_mean_temp    False
cloud_cover_0.0         False
cloud_cover_1.0         False
cloud_cover_2.0         False
cloud_cover_3.0         False
cloud_cover_4.0         False
cloud_cover_5.0         False
cloud_cover_6.0         False
cloud_cover_7.0         False
cloud_cover_8.0         False
precipitation_0         False
precipitation_1         False
precipitation_2         False
precipitation_3         False
precipitation_4         False
snow_depth_0.0          False
snow_depth_1.0          False
dtype: bool

In [32]:
cols_to_move = ['next_1_day_mean_temp','next_2_day_mean_temp','next_3_day_mean_temp']
new_order = [col for col in df.columns if col not in cols_to_move] + cols_to_move
df = df.reindex(columns=new_order)

### single input

In [297]:
X = df.drop(['next_1_day_mean_temp','next_2_day_mean_temp','next_3_day_mean_temp'], axis=1)
y = df[['next_1_day_mean_temp', 'next_2_day_mean_temp', 'next_3_day_mean_temp']]

In [298]:
X.shape

(15064, 22)

In [299]:
# 假设您的 DataFrame 名为 df，形状为 (100, 22)

# 将数据划分为通道
num_channels = 10  # 每个通道包含的行数
num_samples = X.shape[0] - num_channels + 1
channels = []
for i in range(num_samples):
    channel = X.iloc[i:i+num_channels, :]
    channels.append(channel)

# 重新组织形状为 (x, x, x)
x = 10  # 每个通道中的行数
reshaped_X = np.array(channels).reshape(num_samples, x, X.shape[1])

# reshaped_df 的形状为 (num_samples, x, num_channels, num_features)

In [300]:
reshaped_y = y[-num_samples:]

In [301]:
reshaped_X.shape

(15055, 10, 22)

In [302]:
reshaped_y.shape

(15055, 3)

In [303]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(reshaped_X, reshaped_y, test_size=0.2, random_state=42)

# 划分训练集为新的训练集和验证集
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [304]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

torch.manual_seed(42)  # set the random seed

X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

batch_size = 256

# Create DataLoaders for training, validation, and testing
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size)
test_loader = DataLoader(test_dataset, batch_size=batch_size)

In [305]:
X_train.shape

(9635, 10, 22)

In [306]:
import torch
import torch.nn as nn
from scipy.stats import pearsonr

class SingleInputSingleOutputRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, time_step, num_layers, dropout):
        super(SingleInputSingleOutputRNN, self).__init__()

        self.time_step = time_step

        self.hidden_size = hidden_size

        self.num_layers = num_layers

        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True, dropout=dropout)
        #self.rnn = nn.RNN(input_size, hidden_size, num_layers, dropout, batch_first=True)
        #self.fc1 = nn.Linear(hidden_size, 32)
        #self.fc2 = nn.Linear(32, output_size)
        self.fc1 = nn.Linear(time_step * hidden_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, x):
        batch_size = x.size(0)
        sequence_length = x.size(1)

        hidden = self.init_hidden(batch_size) # initialize the hidden state 

        out, hidden = self.rnn(x, hidden)
        #time_step = 3
        out = out[:, -self.time_step:, :]  # 选择最后一个时间步的输出作为最终的输出结果
        #print(out.shape)
        
        out = out.reshape(out.size(0), -1)
        #print(out.shape)
        
        out = self.fc1(out)
        out = self.fc2(out)
        #out = torch.relu(out)
        #out = self.fc2(out)

        return out

    def init_hidden(self, batch_size):
        return torch.zeros(self.num_layers, batch_size, self.hidden_size)

# Define the input tensor
#input_data = torch.randn(15, 10, 22)  # Batch size: 1500, Sequence length: 10, Input size: 22
#target = torch.randn(15, 3)  # Batch size: 15, 3个目标值

In [54]:
# 定义早停函数
def early_stopping(val_loss, patience=10, delta=0):
    if len(val_loss) < patience + 1:
        return False

    best_loss = min(val_loss[:-patience])
    last_loss = val_loss[-1]

    if last_loss > best_loss - delta:
        return True

    return False

In [55]:
from torch.optim.lr_scheduler import StepLR

# 定义模型
model = SingleInputSingleOutputRNN(input_size=22, hidden_size=25, output_size=3, time_step=1, num_layers = 1, dropout = 1.03179779e-02)

# 定义损失函数
criterion = nn.MSELoss()  # 使用均方误差损失函数

# 定义优化器
optimizer = torch.optim.Adam(model.parameters(), lr=8.68102041e-04, weight_decay = 5.77752695e-03)

# 训练模型
num_epochs = 500

train_loss_history = []
val_loss_history = []
best_model_state = None

# 学习率衰减
step_size = 15
gamma = 0.9
scheduler = StepLR(optimizer, step_size=step_size, gamma=gamma)

# 训练模型
for epoch in range(num_epochs):
    model.train()
    train_total_loss = 0.0
    for i, (X_batch, y_batch) in enumerate(train_loader):
        # Clear gradients from the previous iteration
        optimizer.zero_grad()

        # Forward pass: compute model predictions
        predictions = model(X_batch)
        #print('here is prediction：', predictions.shape)

        # Compute the loss
        loss = criterion(predictions, y_batch)
        #print('here is loss：', loss.item())

        # Backpropagation: compute gradients of the loss with respect to model parameters
        loss.backward()

        # Optimization: update model parameters using the gradients
        optimizer.step()

        # Accumulate the total loss for this epoch

        train_total_loss += loss.item()

        #print(total_loss)
    # Calculate the average loss for this epoch
    scheduler.step()
    train_loss = train_total_loss / len(train_loader)
    train_loss_history.append(train_loss)
        #print('toatl loss: ', total_loss)
        #print(len(train_loader))
        #print('average loss: ', average_loss)

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {train_loss:.4f}')

    model.eval()
    with torch.no_grad():
        val_total_loss = 0.0
        for batch_X, batch_y in val_loader:
            predictions = model(batch_X)
            loss = criterion(predictions, batch_y)
            val_total_loss += loss.item()
        validation_loss = val_total_loss / len(val_loader)
        val_loss_history.append(validation_loss)

        # 检查是否早停
    if early_stopping(val_loss_history, patience = 30, delta = 0.001):
        print("\n Early stopping triggered!")
        best_model_state = model.state_dict()
        break
# 完成训练后，可以使用模型进行预测或进行评估。

# 使用训练好的模型进行预测

model.eval()
with torch.no_grad():
    val_total_loss = 0.0
    for batch_X, batch_y in val_loader:
        predictions = model(batch_X)
        loss = criterion(predictions, batch_y)
        val_total_loss += loss.item()
    validation_loss = val_total_loss / len(val_loader)    
    print(validation_loss)

NameError: name 'SingleInputSingleOutputRNN' is not defined

### multiple input

In [33]:
# 将温度和其他天气指标分开
selected_columns = ['max_temp', 'min_temp', 'mean_temp']

# 第一个 DataFrame 包含所选的列
df1 = df[selected_columns]

# 第二个 DataFrame 包含除了所选的列之外的其他列
df2 = df.drop(columns=selected_columns)

In [34]:
X1 = df1
X2 = df2.drop(['next_1_day_mean_temp','next_2_day_mean_temp','next_3_day_mean_temp'], axis=1)
y = df2[['next_1_day_mean_temp', 'next_2_day_mean_temp', 'next_3_day_mean_temp']]

In [35]:
# 假设您的 DataFrame 名为 df，形状为 (100, 22)

# 将数据划分为通道
num_channels = 10  # 每个通道包含的行数
num_samples = X1.shape[0] - num_channels + 1
channels = []
for i in range(num_samples):
    channel = X1.iloc[i:i+num_channels, :]
    channels.append(channel)

# 重新组织形状为 (x, x, x)
x = 10  # 每个通道中的行数
reshaped_X1 = np.array(channels).reshape(num_samples, x, X1.shape[1])

# reshaped_df 的形状为 (num_samples, x, num_channels, num_features)

In [36]:
reshaped_X1.shape

(15055, 10, 3)

In [37]:
# 假设您的 DataFrame 名为 df，形状为 (100, 22)

# 将数据划分为通道
num_channels = 10  # 每个通道包含的行数
num_samples = X2.shape[0] - num_channels + 1
channels = []
for i in range(num_samples):
    channel = X2.iloc[i:i+num_channels, :]
    channels.append(channel)

# 重新组织形状为 (x, x, x)
x = 10  # 每个通道中的行数
reshaped_X2 = np.array(channels).reshape(num_samples, x, X2.shape[1])

# reshaped_df 的形状为 (num_samples, x, num_channels, num_features)

In [38]:
reshaped_X2.shape

(15055, 10, 19)

In [39]:
reshaped_y = y[-num_samples:]

In [40]:
reshaped_y.shape

(15055, 3)

In [41]:
from sklearn.model_selection import train_test_split

X1_train, X1_temp, X2_train, X2_temp, y_train, y_temp = train_test_split(reshaped_X1, reshaped_X2, reshaped_y, test_size=0.3, random_state=42)

# 划分训练集为新的训练集和验证集
X1_val, X1_test, X2_val, X2_test, y_val, y_test = train_test_split(X1_temp, X2_temp, y_temp, test_size=0.5, random_state=42)

In [43]:
import torch
import torch.nn as nn
from torch.optim.lr_scheduler import StepLR


# 转换为 PyTorch 张量
torch.manual_seed(42)  # set the random seed

X1_train = torch.tensor(X1_train, dtype=torch.float32)
X1_val = torch.tensor(X1_val, dtype=torch.float32)
X1_test = torch.tensor(X1_test, dtype=torch.float32)

X2_train = torch.tensor(X2_train, dtype=torch.float32)
X2_val = torch.tensor(X2_val, dtype=torch.float32)
X2_test = torch.tensor(X2_test, dtype=torch.float32)

y_train = torch.tensor(y_train.values, dtype=torch.float32)
y_val = torch.tensor(y_val.values, dtype=torch.float32)
y_test = torch.tensor(y_test.values, dtype=torch.float32)

In [44]:
# 创建数据集和数据加载器
train_dataset = torch.utils.data.TensorDataset(X1_train, X2_train, y_train)
val_dataset = torch.utils.data.TensorDataset(X1_val, X2_val, y_val)
test_dataset = torch.utils.data.TensorDataset(X1_test, X2_test, y_test)

batch_size = 64  # 设置适当的批次大小

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [59]:
import torch
import torch.nn as nn

class MultiInputSingleOutputRNN(nn.Module):
    def __init__(self, input_size1, input_size2, hidden_size1, hidden_size2, output_size, time_step, num_layers1, num_layers2, dropout):
        super(MultiInputSingleOutputRNN, self).__init__()
        
        self.time_step = time_step
        
        self.hidden_size1 = hidden_size1
        self.hidden_size2 = hidden_size2
        
        self.num_layers1 = num_layers1
        self.num_layers2 = num_layers2
        

        self.rnn1 = nn.RNN(input_size1, hidden_size1, num_layers1, batch_first=True, dropout = dropout)
        self.rnn2 = nn.RNN(input_size2, hidden_size2, num_layers2, batch_first=True, dropout = dropout)
        self.fc1 = nn.Linear( (hidden_size1+hidden_size2) * self.time_step, output_size)        
        #self.fc2 = nn.Linear((hidden_size1+hidden_size2), output_size)

    def forward(self, input1, input2):
        batch_size = input1.size(0)
        sequence_length = input1.size(1)

        # Process input1 with rnn1
        hidden1 = self.init_hidden(self.num_layers1, batch_size, self.hidden_size1)
        out1, hidden1 = self.rnn1(input1, hidden1)
        #print(out1.shape)
        
        # Process input2 with rnn2
        hidden2 = self.init_hidden(self.num_layers2, batch_size, self.hidden_size2)
        out2, hidden2 = self.rnn2(input2, hidden2)
        #print(out2.shape)

        # Concatenate the outputs of rnn1, rnn2, and rnn3 along the feature dimension
        combined_output = torch.cat((out1, out2), dim=2)
        #print(combined_output.shape)
        
        out = combined_output[:, -self.time_step:, :]  
        #print(out.shape)
        
        #out = out.view(batch_size, -1)
        out = out.view(out.size(0), -1)
        #print(out.shape)
        
        out = self.fc1(out)
        
        #out = self.fc2(out)

        return out

    def init_hidden(self, num_layers, batch_size, hidden_size):
        return torch.zeros(num_layers, batch_size, hidden_size)

In [60]:
# Define the model
#model = MultiInputSingleOutputRNN(input_size1=22, input_size2=15, input_size3=10, hidden_size=16, output_size=3)
model = MultiInputSingleOutputRNN(input_size1=3, input_size2=19, hidden_size1=25, hidden_size2=50, output_size=3, time_step=1, num_layers1 = 1, num_layers2 = 2, dropout = 0.1)

# Define the loss function
criterion = nn.MSELoss()  # Using Mean Squared Error (MSE) loss function

# Define the optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=8.68102041e-04, weight_decay = 5.77752695e-03)

# Train the model
num_epochs = 500

train_loss_history = []
val_loss_history = []
best_model_state = None

# 学习率衰减
step_size = 15
gamma = 0.9
scheduler = StepLR(optimizer, step_size=step_size, gamma=gamma)

# 训练模型
for epoch in range(num_epochs):
    model.train()
    train_total_loss = 0.0
    for i, (X1_batch, X2_batch, y_batch) in enumerate(train_loader):
        # Clear gradients from the previous iteration
        optimizer.zero_grad()

        # Forward pass: compute model predictions
        predictions = model(X1_batch, X2_batch)
        #print('here is prediction：', predictions.shape)

        # Compute the loss
        loss = criterion(predictions, y_batch)
        #print('here is loss：', loss.item())

        # Backpropagation: compute gradients of the loss with respect to model parameters
        loss.backward()

        # Optimization: update model parameters using the gradients
        optimizer.step()

        # Accumulate the total loss for this epoch

        train_total_loss += loss.item()

        #print(total_loss)
    # Calculate the average loss for this epoch
    scheduler.step()
    train_loss = train_total_loss / len(train_loader)
    train_loss_history.append(train_loss)
        #print('toatl loss: ', total_loss)
        #print(len(train_loader))
        #print('average loss: ', average_loss)

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {train_loss:.4f}')

    model.eval()
    with torch.no_grad():
        val_total_loss = 0.0
        for batch_X1, batch_X2, batch_y in val_loader:
            predictions = model(batch_X1, batch_X2)
            loss = criterion(predictions, batch_y)
            val_total_loss += loss.item()
        validation_loss = val_total_loss / len(val_loader)
        val_loss_history.append(validation_loss)

        # 检查是否早停
    if early_stopping(val_loss_history, patience = 30, delta = 0.001):
        print("\n Early stopping triggered!")
        best_model_state = model.state_dict()
        break
# 完成训练后，可以使用模型进行预测或进行评估。

# 使用训练好的模型进行预测

model.eval()
with torch.no_grad():
    val_total_loss = 0.0
    for batch_X1, batch_X2, batch_y in val_loader:
        predictions = model(batch_X1, batch_X2)
        loss = criterion(predictions, batch_y)
        val_total_loss += loss.item()
    validation_loss = val_total_loss / len(val_loader)    
    print(validation_loss)

D:\Anaconda\lib\site-packages\torch\nn\modules\rnn.py:71: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "

Epoch [10/500], Loss: 6.4863
Epoch [20/500], Loss: 4.4917
Epoch [30/500], Loss: 3.7595
Epoch [40/500], Loss: 3.5455
Epoch [50/500], Loss: 3.4894
Epoch [60/500], Loss: 3.4703
Epoch [70/500], Loss: 3.4495

 Early stopping triggered!
3.6461234754986234

In [ ]:
with torch.no_grad():      
    # Forward pass
    #output = model(input1, input2, input3)
    predictions = model(input1, input2)

    test_mse = nn.MSELoss()(predictions, target)
    
    test_mae = nn.L1Loss()(predictions, target)
    
    test_rmse = torch.sqrt(test_mse)
    
    absolute_errors = torch.abs(predictions - target)
    test_mdae = torch.median(absolute_errors)

    percentage_errors = absolute_errors / target
    percentage_errors = percentage_errors[~torch.isinf(percentage_errors) & ~torch.isnan(percentage_errors)]
    test_mape = torch.mean(torch.abs(percentage_errors)) * 1000
    
    squared_percentage_errors = torch.pow(percentage_errors * 100, 2)
    squared_percentage_errors = squared_percentage_errors[~torch.isinf(squared_percentage_errors)]
    mean_squared_percentage_error = torch.mean(squared_percentage_errors)
    test_rmspe = torch.sqrt(mean_squared_percentage_error)
    
    batch_size = 100
    num_batches = predictions.shape[0] // batch_size
    pearson_coeffs = []
    for i in range(num_batches):
        start_idx = i * batch_size
        end_idx = (i + 1) * batch_size

        predictions_batch = predictions[start_idx:end_idx].detach().numpy().flatten()
        target_data_batch = target[start_idx:end_idx].numpy().flatten()
        pearson_coefficients, _ = pearsonr(predictions_batch, target_data_batch)
        pearson_coeffs.append(pearson_coefficients)
    pearson_coefficient = np.mean(pearson_coeffs)
    
    def index_of_agreement(predictions, observations):
        numerator = torch.sum(torch.square(observations - predictions))
        denominator = torch.sum(torch.square(torch.abs(predictions - torch.mean(observations)) + torch.abs(observations - torch.mean(observations))))
        ioa = 1 - (numerator / denominator)
        return ioa
    
    ioa = index_of_agreement(predictions, target)
    
    
    print(f'MSE: {test_mse.item():.4f}')
    print(f'RMSE: {test_rmse.item():.4f}')
    print(f'MAE: {test_mae.item():.4f}')
    print(f'MdAE: {test_mdae.item():.4f}')
    print(f'MAPE: {test_mape.item():.4f}')
    print(f'RMSPE: {test_rmspe.item():.4f}')
    print(f'Pearson Coefficient: {pearson_coefficient}')
    print(f'Index of Agreement (IoA): {ioa:.4f}')